#!/usr/bin/env python3
"""
Shape the Pujo Personality's fixed lines of type into SVG path data.

Two reasons, one fix:
- Satori (next/og) does not do full OpenType shaping, so Bengali conjuncts
  and vowel signs come out wrong in server-rendered link previews.
- The house Latin faces are licensed web fonts. They are served to browsers
  from public/fonts, and are not converted or copied anywhere else.

So HarfBuzz shapes each line in lib/pujo-personality/og-lines.ts once, from
the web fonts in public/fonts, and fontTools flattens the glyphs into one path
per line. Output, in units of 1000 per em, y down, baseline at y = 0:

    lib/pujo-personality/bengali-paths.ts   names and fixed Bengali lines
                                            (the share-card canvas uses these too)
    lib/pujo-personality/og-latin-paths.ts  the previews' Latin lines

The same goes for Find your Ashtami date's match card preview: the lines in
lib/ashtami-date/og-lines.ts become lib/ashtami-date/og-paths.ts.

Run from frontend/ after changing a name or a line, naming the set to shape
(both when none is named):

    python3 scripts/pujo/generate-paths.py [pujo] [ashtami]

Needs python3 with fontTools and brotli, hb-shape (HarfBuzz) and npx.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[2]
LIB = ROOT / 'lib/pujo-personality'
UPEM = 1000

FACES = {
    'bengali': (ROOT / 'public/fonts/noto-sans-bengali-variable.woff2', {'wght': 700, 'wdth': 100}),
    'display': (ROOT / 'public/fonts/clear-sans-display.woff2', None),
    'text': (ROOT / 'public/fonts/clear-sans-text.woff2', None),
}


def og_lines(source='lib/pujo-personality/og-lines.ts'):
    script = f"import('./{source}').then((m) => console.log(JSON.stringify(m.OG_LINES)))"
    out = subprocess.run(['npx', 'tsx', '-e', script], cwd=ROOT, check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def load_face(path, axes, tmp):
    font = TTFont(path)
    if axes:
        instancer.instantiateVariableFont(font, axes, inplace=True)
    font.flavor = None
    static = Path(tmp) / f'{path.stem}.ttf'
    font.save(static)
    return font, static


def shape(font_file, text):
    out = subprocess.run(
        ['hb-shape', '--output-format=json', '--no-glyph-names', str(font_file), text],
        check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(out)


def outline(font, font_file, text, tracking):
    order = font.getGlyphOrder()
    glyphs = font.getGlyphSet()
    k = UPEM / font['head'].unitsPerEm
    pen = SVGPathPen(glyphs, ntos=lambda v: str(round(v)))
    bounds = BoundsPen(glyphs)
    x = 0.0
    shaped = shape(font_file, text)
    for i, g in enumerate(shaped):
        transform = (k, 0, 0, -k, (x + g['dx']) * k, -g['dy'] * k)
        glyphs[order[g['g']]].draw(TransformPen(pen, transform))
        glyphs[order[g['g']]].draw(TransformPen(bounds, transform))
        x += g['ax'] + (tracking * font['head'].unitsPerEm if i < len(shaped) - 1 else 0)
    if bounds.bounds is None:
        sys.exit(f'Nothing drawn for {text!r}')
    return {
        'd': pen.getCommands(),
        'advance': round(x * k),
        'box': [round(v) for v in bounds.bounds],
    }


def module(doc, entries, source='lib/pujo-personality/og-lines.ts'):
    return f'''/*
 * Generated by scripts/pujo/generate-paths.py from {source}.
 * Do not edit by hand.
 *
 * {doc}
 * Units are 1000 per em, y points down, the baseline is y = 0. box is
 * [xMin, yMin, xMax, yMax] of the ink.
 */

export type TypePath = {{ d: string; advance: number; box: [number, number, number, number] }}

export const UNITS_PER_EM = {UPEM}

export const PATHS: Record<string, TypePath> = {json.dumps(entries, ensure_ascii=False, indent=2)}
'''


def shape_all(lines, faces):
    shaped = {}
    for line in lines:
        font, font_file = faces[line['face']]
        shaped[(line['face'], line['text'])] = outline(font, font_file, line['text'], line['tracking'])
    return shaped


def main():
    sets = set(sys.argv[1:]) or {'pujo', 'ashtami'}
    unknown = sets - {'pujo', 'ashtami'}
    if unknown:
        sys.exit(f'Unknown set: {", ".join(sorted(unknown))}. Use pujo, ashtami or both.')
    with tempfile.TemporaryDirectory() as tmp:
        faces = {name: load_face(path, axes, tmp) for name, (path, axes) in FACES.items()}

        if 'pujo' in sets:
            bengali, latin = {}, {}
            for (face, text), shaped in shape_all(og_lines(), faces).items():
                if face == 'bengali':
                    bengali[text] = shaped
                else:
                    latin[f"{face}:{text}"] = shaped
            (LIB / 'bengali-paths.ts').write_text(module(
                'Noto Sans Bengali at wght 700, shaped by HarfBuzz, because Satori cannot shape Bengali.',
                bengali), 'utf-8')
            (LIB / 'og-latin-paths.ts').write_text(module(
                'Clear Sans Display and Text, for the link previews only. Keys are "display:" or "text:" and the line.',
                latin), 'utf-8')
            print(f'Wrote {len(bengali)} Bengali and {len(latin)} Latin lines')

        if 'ashtami' in sets:
            source = 'lib/ashtami-date/og-lines.ts'
            lines = {f"{face}:{text}": shaped for (face, text), shaped in shape_all(og_lines(source), faces).items()}
            (ROOT / 'lib/ashtami-date/og-paths.ts').write_text(module(
                'The match card preview: Clear Sans Display and Text, and Noto Sans Bengali at wght 700. '
                'Keys are "display:", "text:" or "bengali:" and the line.',
                lines, source), 'utf-8')
            print(f'Wrote {len(lines)} lines for the match card')


if __name__ == '__main__':
    main()
